Vagrant.configure("2") do |config|
config.vm.box = "debian/buster64"
# Add memory, 2 CPU, 
config.vm.network "private_network", ip: "192.168.33.4" 
config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
  end    
  config.vm.provision "shell" do |s|
    s.inline = <<-SHELL
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCaaucExTV0c9kdQOQOgQZ5StIEcSRZh+dihJuYi43Xq9eyCOW3TKmmQY3n2MtSC+EDqdtzzQggbq1o9dJp3KxyhQMXViV8d7ACkGOHabxDVoSymnQOpSoevSwTmPehsri30dPCb9x3bUw56DKG+arfMiTgv4XLD7gfhKY/Uu7v/YoNY6Ca8m3Uh8eG0I3sSy5No2lBPF/3YFVYXKRLpz78zTFtpDzBilrK8XF7deVEO+0MtgyscjMfd1pDhEvjM6o3i2amwyjnWgiKPWwK2f5VJYyf560tA6LFdPbsakpQ5Ezd9aL5SPk1WO7GbGeOzpEKD8ppXwJG8T0jtNQN/CIgbMejEYpzcT2Ung9VRSjQMtwueqsZq914RNtb7YVDnd9uJoG2Tkvwsk3PbghYfUCtimVol5R6DaMwZW7WqqRLO2aEfZ1M7aL97bJd7gA/hqTK/3mUJoOV60nvCywB0pGm/0HjN/x+uaGhd5T6JvDyZ+7cHLamq+QF5RLis6+z+jE= vagrant@buster
      " >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end
end